### PR TITLE
please merge

### PR DESCRIPTION
**Pull request by Sumyak-Jain**
just changed my username so updated .md with the new username

### CODE REVIEW

**Comment by Sumyak-Jain** [comment]
i  have only made this Sumyak_Jain.md  but now I have changed my github username so I have updated it

**Comment by stanly-johnson** [comment]
Hi @Sumyak-Jain, Pls resolve the conflicts.

**Comment by Sumyak-Jain** [comment]
resolved the issue which was found earlier
also please can you label my PR as "hacktoberfest-accepted" and merge

**Comment by Sumyak-Jain** [comment]
hi @stanly-johnson 
resolved the issue which was found earlier
also please can you label my PR as "hacktoberfest-accepted" and merge

**Comment by stanly-johnson** [comment]
Will merge the new PR at #278 
Closing this

**Pull request closed without merging**
