### PR TITLE
Contribute with leapcode badge

### PR DESCRIPTION
**Pull request by stanly-johnson**
[Preview](https://github.com/stanly-johnson/landingpage/blob/stanly-leapcode-badge/README.md)

Contribute with leapcode badge that takes the user to the leapcode login page. Once we have urls setup for individual projects we can put up url to project page instead and create similar PRs to the project readme files.

### CODE REVIEW

**Comment by stanly-johnson** [comment]
@atulsuresh is this ok?

**Comment by atulsuresh** [comment]
should we increase the size of the badge? something of [this size](https://www.herokucdn.com/deploy/button.svg)

**Comment by stanly-johnson** [comment]
@atulsuresh done

**Comment by atulsuresh** [comment]
looks great!

**Comment by atulsuresh** [comment]
should we push this now or wait for nextjs release?

**Comment by stanly-johnson** [comment]
I think we should push, we can update the link after nextjs release

**Comment by atulsuresh** [comment]
works!

**Review by atulsuresh — APPROVED** [review]

**Pull request merged**
